logging:
  level:
    root: DEBUG
    sun.rmi: INFO
    org.mongodb.driver: INFO
    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO

server:
  servlet:
    session:
      timeout: 1h

spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.12/jakduk_test
    elasticsearch:
      repositories:
        enabled: false
  rabbitmq:
    addresses: 192.168.0.15
    username: admin
    password: wkrenakstp@
    listener:
      simple:
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
          max-attempts: 3

jakduk:
  api-server-url: http://localhost:8080
  web-server-url: http://localhost:3000
  remember-me-expiration: 7200 # 2 hours
  elasticsearch:
    host-and-port:
      - 192.168.0.18:9200
    index-board: jakduk_dev_board
    index-gallery: jakduk_dev_gallery
    index-search-word: jakduk_dev_search_word
    bulk-actions: 10000
    bulk-concurrent-requests: 2
    bulk-flush-interval-seconds: 10
    bulk-size-mb: 50
  rabbitmq:
    exchange-name: jakduk-dev
    queues:
      email:
        binding-queue-name: dev.email
        binding-routing-key: dev.email.*
        enabled: false
      elasticsearch:
        binding-queue-name: dev.elasticsearch
        binding-routing-key: dev.elasticsearch.*
        enabled: true
    routing-keys:
      email-welcome: dev.email.welcome
      email-reset-password: dev.email.reset-password
      elasticsearch-index-document-article: dev.elasticsearch.index-document-article
      elasticsearch-delete-document-article: dev.elasticsearch.delete-document-article
      elasticsearch-index-document-article-comment: dev.elasticsearch.index-document-article-comment
      elasticsearch-delete-document-article-comment: dev.elasticsearch.delete-document-article-comment
      elasticsearch-index-document-gallery: dev.elasticsearch.index-document-gallery
      elasticsearch-delete-document-gallery: dev.elasticsearch.delete-document-gallery
      elasticsearch-index-document-search-word: dev.elasticsearch.index-document-search-word
  storage:
    image-path: /Users/pyohwanjang/storage/image/
    thumbnail-path: /Users/pyohwanjang/storage/thumbnail/
    user-picture-large-path: /Users/pyohwanjang/storage/user/picture/large/
    user-picture-small-path: /Users/pyohwanjang/storage/user/picture/small/